category:
    path:     /category
    defaults: { _controller: CustomBookBundle:Category:index }

category_add:
    path:     /category/add
    defaults: { _controller: CustomBookBundle:Category:add }


product_list:
    path:     /product/{page}
    defaults: { _controller: CustomBookBundle:Product:index, page: 1 }
    requirements:
            page:  \d+



product_add:
    path:     /product/add
    defaults: { _controller: CustomBookBundle:Product:add }


product_sample:
    path:     /product/sample
    defaults: { _controller: CustomBookBundle:Product:sample }

product_test:
    path:     /product/test
    defaults: { _controller: CustomBookBundle:Product:test }



custom_book_homepage:
    path:     /hello
    defaults: { _controller: CustomBookBundle:Default:index }


test_service:
    path:     /test_service/{name}
    defaults: { _controller: CustomBookBundle:Default:service }



login:
  path: /login
  defaults: { _controller: CustomBookBundle:Security:login }

login_check:
  path: /login_check

logout:
  pattern: /logout
