#parameters:
#    cvuorinen_example.greeter.class: CustomBookBundle\Service\Greeter
#    cvuorinen_example.greeter.greeting: "Hallo"
#
#services:
#    cvuorinen_example.greeter:
#        class: %cvuorinen_example.greeter.class%
#        arguments:
#            - %cvuorinen_example.greeter.greeting%
#            - @translator


parameters:
    # ...
    mailer.transport: sendmail


services:
    custombook.greeter:
        class:        CustomBookBundle\Service\Greeter
        arguments:    [Hallo]

    book.mailer:
        class:        CustomBookBundle\Service\Mailer
        arguments:    [sendmail]

    book.foo:
        class:        CustomBookBundle\Service\Foo
        arguments:    [@doctrine.orm.entity_manager]


    mailer:
        class:     CustomBookBundle\Service\Mailer
        arguments: ['%mailer.transport%']
    book.newsletter_manager:
        class:     CustomBookBundle\Service\NewsletterManager
        calls:
            - [setMailer, ['@mailer']]