# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
#security:
#    encoders:
#      Symfony\Component\Security\Core\User\User: plaintext
#    role_hierarchy:
#      ROLE_ADMIN: [ROLE_USER]
#    providers:
#      chain_provider:
#        chain:
#          providers: [in_memory]
#      in_memory:
#        memory:
#          users:
#            user: {password: 123456, roles: ROLE_USER}
#            admin: {password: 123456, roles: ROLE_ADMIN}
#            super: {password: 123456, roles: ROLE_SUPER_ADMIN}
#
#    role_hierarchy:
#            ROLE_ADMIN:       ROLE_USER
#            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#
#    firewalls:
#      main:
#        pattern: /.*
#        form_login:
#          login_path: /login
#          check_path: /login_check
#          default_target_path: /book
#        logout:
#          path: /logout
#          target: /book
#        security: true
#        anonymous: true

# app/config/security.yml
security:
    encoders:
        CustomBookBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        administrators:
            entity: { class: CustomBookBundle:User }

    firewalls:
          main:
            pattern: /.*
            form_login:
              login_path: /login
              check_path: /login_check
              default_target_path: /book
            logout:
              path: /logout
              target: /book
            security: true
            anonymous: true

    access_control:

