<?php

namespace CustomBookBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($params = array())
    {

        if(isset($params['category']))
        {

        }
    }

    /*
     * Get list items pagination
     */
    public function getListItems($category, $itemPerPage, $page)
    {
        $query = $this->createQueryBuilder('i')
            ->join('i.feed', 'f')
            ->addSelect('f')
            ->where('f.category= :category')
            ->setParameter('category', $category)
            ->getQuery();

        $query->setFirstResult(($page - 1) * $itemPerPage)
            ->setMaxResults($itemPerPage);
        return $query->getResult();
    }


    /*
     * Count total items
     */
    public function countTotalItems($params = array())
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(i.id) as total FROM AppBundle:FeedItem  i
                JOIN i.feed f
                WHERE f.category= :category')
            ->setParameter('category', $params);


        return $query->getSingleScalarResult();
    }

}
